use bytes::Bytes;
use open_claude_router::{
    sse::{aggregate_chat_sse, aggregate_responses_sse},
    transform::{
        ChatToolNameMap, prepare_chat_request_with_tool_names, transform_anthropic_request,
        transform_chat_json_response_with_tool_names, transform_responses_json,
    },
};
use serde_json::Value;

const PREVIEW_CHARS: usize = 240;

/// Values reconstructed from a terminal upstream response body, reusing the
/// router's own SSE aggregators so the semantics match forwarding exactly.
/// `anthropic_response` replays the router's response conversion on the
/// aggregated upstream payload — the Anthropic-protocol view the client
/// received (final-state equivalent for streams).
#[derive(Default)]
pub struct Derived {
    pub agg_response: Option<Value>,
    pub anthropic_response: Option<Value>,
    pub finish_reason: Option<String>,
    pub input_tokens: Option<i64>,
    pub output_tokens: Option<i64>,
    pub cached_tokens: Option<i64>,
    pub cache_write_tokens: Option<i64>,
    pub reasoning_tokens: Option<i64>,
    pub preview: Option<String>,
}

/// How the router converted this exchange's upstream response for its client,
/// rebuilt from the recorded request bodies so a replay matches what the
/// client actually received: the thinking-omission flag comes from the client
/// request, and the chat tool-name aliases are regenerated by re-running the
/// router's own (deterministic) request preparation.
#[derive(Default)]
pub struct ReplayContext {
    omit_thinking: bool,
    chat_tool_names: ChatToolNameMap,
}

impl ReplayContext {
    pub fn from_recorded(
        format: &str,
        client_req_body: Option<&str>,
        req_body: Option<&str>,
    ) -> Self {
        let client = client_req_body.and_then(|text| serde_json::from_str::<Value>(text).ok());
        let omit_thinking = client
            .as_ref()
            .and_then(|payload| payload.pointer("/thinking/display"))
            .and_then(Value::as_str)
            == Some("omitted");
        // Responses-format replays don't rename tools, so only chat needs a map.
        let chat_tool_names = if format == "responses" {
            ChatToolNameMap::default()
        } else {
            rebuild_chat_tool_names(client.as_ref(), req_body)
        };
        Self {
            omit_thinking,
            chat_tool_names,
        }
    }
}

/// The router aliases Chat-illegal tool names *before* logging the outbound
/// body, so the map has to be regenerated from the original client request.
/// Rows without a stored client request fall back to preparing the recorded
/// outbound body: its names are already wire-legal, which yields the identity
/// map (the pre-replay-context behavior).
fn rebuild_chat_tool_names(client: Option<&Value>, req_body: Option<&str>) -> ChatToolNameMap {
    if let Some(payload) = client
        && let Ok(mut outbound) = transform_anthropic_request(payload)
    {
        return prepare_chat_request_with_tool_names(&mut outbound);
    }
    req_body
        .and_then(|text| serde_json::from_str::<Value>(text).ok())
        .map(|mut outbound| prepare_chat_request_with_tool_names(&mut outbound))
        .unwrap_or_default()
}

pub fn derive_response(
    format: &str,
    content_type: &str,
    body_json: Option<&Value>,
    body_text: Option<&str>,
    replay: &ReplayContext,
) -> Derived {
    let final_json = if is_sse(content_type, body_text) {
        let raw = Bytes::from(body_text.unwrap_or_default().as_bytes().to_vec());
        let aggregated = match format {
            "responses" => aggregate_responses_sse(raw),
            _ => aggregate_chat_sse(raw),
        };
        // Cancelled or truncated streams legitimately fail aggregation;
        // the dashboard then falls back to the raw event view.
        aggregated.ok()
    } else if let Some(body) = body_json {
        Some(body.clone())
    } else {
        body_text.and_then(|text| serde_json::from_str::<Value>(text).ok())
    };

    let Some(final_json) = final_json else {
        return Derived::default();
    };
    let mut derived = match format {
        "responses" => extract_responses(&final_json),
        _ => extract_chat(&final_json),
    };
    derived.anthropic_response = replay_anthropic(format, &final_json, replay);
    derived.agg_response = Some(final_json);
    derived
}

/// Replays the router's own response transform to produce the client-side
/// (Anthropic Messages) view of the upstream response, honoring the
/// thinking-omission flag and tool-name map the router used originally.
pub fn replay_anthropic(format: &str, upstream: &Value, replay: &ReplayContext) -> Option<Value> {
    match format {
        "responses" => transform_responses_json(upstream, replay.omit_thinking).ok(),
        _ => transform_chat_json_response_with_tool_names(
            upstream,
            replay.omit_thinking,
            &replay.chat_tool_names,
        )
        .ok(),
    }
}

fn is_sse(content_type: &str, body_text: Option<&str>) -> bool {
    if content_type
        .to_ascii_lowercase()
        .contains("text/event-stream")
    {
        return true;
    }
    body_text.is_some_and(|text| {
        let head = text.trim_start();
        head.starts_with("data:") || head.starts_with("event:")
    })
}

fn extract_chat(response: &Value) -> Derived {
    let usage = response.get("usage");
    let choice = response.pointer("/choices/0");
    let message = choice.and_then(|choice| choice.get("message"));
    let mut preview = message
        .and_then(|message| message.get("content"))
        .and_then(Value::as_str)
        .map(str::to_owned)
        .unwrap_or_default();
    if preview.trim().is_empty()
        && let Some(calls) = message
            .and_then(|message| message.get("tool_calls"))
            .and_then(Value::as_array)
    {
        let names = calls
            .iter()
            .filter_map(|call| call.pointer("/function/name").and_then(Value::as_str))
            .collect::<Vec<_>>()
            .join(", ");
        preview = format!("→ tool_calls: {names}");
    }
    Derived {
        agg_response: None,
        anthropic_response: None,
        finish_reason: choice
            .and_then(|choice| choice.get("finish_reason"))
            .and_then(Value::as_str)
            .map(str::to_owned),
        input_tokens: int_at(usage, "/prompt_tokens"),
        output_tokens: int_at(usage, "/completion_tokens"),
        cached_tokens: int_at(usage, "/prompt_tokens_details/cached_tokens"),
        cache_write_tokens: int_at(usage, "/prompt_tokens_details/cache_write_tokens"),
        reasoning_tokens: int_at(usage, "/completion_tokens_details/reasoning_tokens"),
        preview: non_empty_preview(preview),
    }
}

fn extract_responses(response: &Value) -> Derived {
    let usage = response.get("usage");
    let mut preview = String::new();
    let mut tool_names = Vec::new();
    if let Some(output) = response.get("output").and_then(Value::as_array) {
        for item in output {
            match item.get("type").and_then(Value::as_str) {
                Some("message") => {
                    if let Some(parts) = item.get("content").and_then(Value::as_array) {
                        for part in parts {
                            if part.get("type").and_then(Value::as_str) == Some("output_text")
                                && let Some(text) = part.get("text").and_then(Value::as_str)
                            {
                                preview.push_str(text);
                            }
                        }
                    }
                }
                Some("function_call") => {
                    if let Some(name) = item.get("name").and_then(Value::as_str) {
                        tool_names.push(name.to_owned());
                    }
                }
                _ => {}
            }
        }
    }
    if preview.trim().is_empty() && !tool_names.is_empty() {
        preview = format!("→ function_call: {}", tool_names.join(", "));
    }
    let mut finish = response
        .get("status")
        .and_then(Value::as_str)
        .map(str::to_owned);
    if let Some(reason) = response
        .pointer("/incomplete_details/reason")
        .and_then(Value::as_str)
    {
        finish = Some(format!("incomplete: {reason}"));
    }
    Derived {
        agg_response: None,
        anthropic_response: None,
        finish_reason: finish,
        input_tokens: int_at(usage, "/input_tokens"),
        output_tokens: int_at(usage, "/output_tokens"),
        cached_tokens: int_at(usage, "/input_tokens_details/cached_tokens"),
        cache_write_tokens: int_at(usage, "/input_tokens_details/cache_write_tokens"),
        reasoning_tokens: int_at(usage, "/output_tokens_details/reasoning_tokens"),
        preview: non_empty_preview(preview),
    }
}

fn int_at(root: Option<&Value>, pointer: &str) -> Option<i64> {
    root?.pointer(pointer)?.as_i64()
}

fn non_empty_preview(text: String) -> Option<String> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return None;
    }
    let mut chars = trimmed.chars();
    let mut bounded = chars.by_ref().take(PREVIEW_CHARS).collect::<String>();
    if chars.next().is_some() {
        bounded.push('…');
    }
    Some(bounded)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn chat_json_body_yields_usage_and_preview() {
        let body = json!({
            "choices": [{
                "finish_reason": "stop",
                "message": {"content": "hello world"}
            }],
            "usage": {
                "prompt_tokens": 12,
                "completion_tokens": 5,
                "prompt_tokens_details": {"cached_tokens": 4, "cache_write_tokens": 3},
                "completion_tokens_details": {"reasoning_tokens": 2}
            }
        });
        let derived = derive_response(
            "chat-completions",
            "application/json",
            Some(&body),
            None,
            &ReplayContext::default(),
        );
        assert_eq!(derived.finish_reason.as_deref(), Some("stop"));
        assert_eq!(derived.input_tokens, Some(12));
        assert_eq!(derived.output_tokens, Some(5));
        assert_eq!(derived.cached_tokens, Some(4));
        assert_eq!(derived.cache_write_tokens, Some(3));
        assert_eq!(derived.reasoning_tokens, Some(2));
        assert_eq!(derived.preview.as_deref(), Some("hello world"));
        assert!(derived.agg_response.is_some());
    }

    #[test]
    fn responses_json_body_yields_cache_write_usage() {
        let body = json!({
            "status": "completed",
            "output": [],
            "usage": {
                "input_tokens": 20,
                "output_tokens": 6,
                "input_tokens_details": {"cached_tokens": 8, "cache_write_tokens": 5},
                "output_tokens_details": {"reasoning_tokens": 2}
            }
        });
        let derived = derive_response(
            "responses",
            "application/json",
            Some(&body),
            None,
            &ReplayContext::default(),
        );
        assert_eq!(derived.input_tokens, Some(20));
        assert_eq!(derived.output_tokens, Some(6));
        assert_eq!(derived.cached_tokens, Some(8));
        assert_eq!(derived.cache_write_tokens, Some(5));
        assert_eq!(derived.reasoning_tokens, Some(2));
    }

    #[test]
    fn chat_sse_stream_is_aggregated() {
        let sse = concat!(
            "data: {\"id\":\"c1\",\"object\":\"chat.completion.chunk\",\"model\":\"m\",\"choices\":[{\"index\":0,\"delta\":{\"role\":\"assistant\",\"content\":\"hi \"}}]}\n\n",
            "data: {\"id\":\"c1\",\"object\":\"chat.completion.chunk\",\"model\":\"m\",\"choices\":[{\"index\":0,\"delta\":{\"content\":\"there\"},\"finish_reason\":\"stop\"}]}\n\n",
            "data: {\"id\":\"c1\",\"object\":\"chat.completion.chunk\",\"model\":\"m\",\"choices\":[],\"usage\":{\"prompt_tokens\":3,\"completion_tokens\":2}}\n\n",
            "data: [DONE]\n\n"
        );
        let derived = derive_response(
            "chat-completions",
            "text/event-stream",
            None,
            Some(sse),
            &ReplayContext::default(),
        );
        assert_eq!(derived.preview.as_deref(), Some("hi there"));
        assert_eq!(derived.finish_reason.as_deref(), Some("stop"));
        assert_eq!(derived.input_tokens, Some(3));
    }

    #[test]
    fn chat_response_is_replayed_into_anthropic_view() {
        let body = json!({
            "id": "c1",
            "model": "m",
            "choices": [{
                "finish_reason": "stop",
                "message": {"role": "assistant", "content": "hello"}
            }],
            "usage": {"prompt_tokens": 3, "completion_tokens": 2}
        });
        let derived = derive_response(
            "chat-completions",
            "application/json",
            Some(&body),
            None,
            &ReplayContext::default(),
        );
        let anthropic = derived.anthropic_response.expect("anthropic view");
        assert_eq!(anthropic["type"], "message");
        assert_eq!(anthropic["role"], "assistant");
        assert_eq!(anthropic["stop_reason"], "end_turn");
        assert_eq!(anthropic["content"][0]["text"], "hello");
    }

    #[test]
    fn cancelled_stream_falls_back_to_raw() {
        let sse = "data: {\"choices\":[{\"index\":0,\"delta\":{\"content\":\"par\"}}]}\n\n";
        let derived = derive_response(
            "chat-completions",
            "text/event-stream",
            None,
            Some(sse),
            &ReplayContext::default(),
        );
        assert!(derived.agg_response.is_none());
        assert!(derived.preview.is_none());
    }

    #[test]
    fn replay_honors_client_thinking_omission() {
        let client = json!({
            "model": "m",
            "max_tokens": 16,
            "thinking": {"type": "enabled", "budget_tokens": 8, "display": "omitted"},
            "messages": [{"role": "user", "content": "hi"}]
        })
        .to_string();
        let upstream = json!({
            "id": "c1",
            "model": "m",
            "choices": [{
                "finish_reason": "stop",
                "message": {"role": "assistant", "content": "x", "reasoning_content": "secret"}
            }]
        });

        let replay = ReplayContext::from_recorded("chat-completions", Some(&client), None);
        let omitted = replay_anthropic("chat-completions", &upstream, &replay).unwrap();
        assert_eq!(omitted["content"][0]["type"], "thinking");
        assert_eq!(omitted["content"][0]["thinking"], "");

        let kept =
            replay_anthropic("chat-completions", &upstream, &ReplayContext::default()).unwrap();
        assert_eq!(kept["content"][0]["thinking"], "secret");
    }

    #[test]
    fn replay_restores_aliased_chat_tool_names() {
        let long_name = "x".repeat(80);
        let client = json!({
            "model": "m",
            "max_tokens": 16,
            "messages": [{"role": "user", "content": "hi"}],
            "tools": [{"name": long_name, "input_schema": {"type": "object"}}]
        });

        // The alias the router put on the wire: rerun its own preparation and
        // read the renamed tool back out of the outbound body.
        let mut outbound = transform_anthropic_request(&client).unwrap();
        prepare_chat_request_with_tool_names(&mut outbound);
        let alias = outbound
            .pointer("/tools/0/function/name")
            .and_then(Value::as_str)
            .unwrap()
            .to_owned();
        assert_ne!(alias, long_name);

        let upstream = json!({
            "id": "c1",
            "model": "m",
            "choices": [{
                "finish_reason": "tool_calls",
                "message": {
                    "role": "assistant",
                    "tool_calls": [{
                        "id": "call_1",
                        "type": "function",
                        "function": {"name": alias, "arguments": "{}"}
                    }]
                }
            }]
        });

        let replay =
            ReplayContext::from_recorded("chat-completions", Some(&client.to_string()), None);
        let anthropic = replay_anthropic("chat-completions", &upstream, &replay).unwrap();
        let tool_use = anthropic["content"]
            .as_array()
            .unwrap()
            .iter()
            .find(|block| block["type"] == "tool_use")
            .unwrap();
        assert_eq!(tool_use["name"], long_name.as_str());
    }
}
